# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: db_development
  encoding: SQL_ASCII
  pool: 5
  
test:
  adapter: postgresql
  database: db_test
  encoding: SQL_ASCII
  pool: 5
